export const eligibleStudents = [
  {
    id: 1,
    name: "Rahul Sharma",
    enrollmentNo: "2023CS001",
    department: "Computer Science",
    cgpa: 8.75,
    company: "Google",
    status: "Eligible"
  },
  {
    id: 2,
    name: "Anjali Singh",
    enrollmentNo: "2023IT021",
    department: "Information Technology",
    cgpa: 9.10,
    company: "Microsoft",
    status: "Eligible"
  },
  {
    id: 3,
    name: "Amit Kumar",
    enrollmentNo: "2023CS002",
    department: "Computer Science",
    cgpa: 8.32,
    company: "Amazon",
    status: "Eligible"
  },
  {
    id: 4,
    name: "Priya Verma",
    enrollmentNo: "2023EC003",
    department: "Electronics",
    cgpa: 7.95,
    company: "TCS",
    status: "Eligible"
  },
  {
    id: 5,
    name: "Rohit Gupta",
    enrollmentNo: "2023ME004",
    department: "Mechanical",
    cgpa: 6.85,
    company: "Infosys",
    status: "Eligible"
  },
  {
    id: 6,
    name: "Sneha Patel",
    enrollmentNo: "2023IT005",
    department: "Information Technology",
    cgpa: 9.25,
    company: "Adobe",
    status: "Eligible"
  },
  {
    id: 7,
    name: "Vikram Singh",
    enrollmentNo: "2023CE006",
    department: "Civil",
    cgpa: 7.42,
    company: "Wipro",
    status: "Eligible"
  },
  {
    id: 8,
    name: "Neha Sharma",
    enrollmentNo: "2023CS007",
    department: "Computer Science",
    cgpa: 8.88,
    company: "Google",
    status: "Eligible"
  },
  {
    id: 9,
    name: "Arjun Mehta",
    enrollmentNo: "2023EE008",
    department: "Electrical",
    cgpa: 7.30,
    company: "Capgemini",
    status: "Eligible"
  },
  {
    id: 10,
    name: "Pooja Yadav",
    enrollmentNo: "2023IT009",
    department: "Information Technology",
    cgpa: 8.67,
    company: "IBM",
    status: "Eligible"
  },
  {
    id: 11,
    name: "Karan Malhotra",
    enrollmentNo: "2023CS010",
    department: "Computer Science",
    cgpa: 7.15,
    company: "Accenture",
    status: "Eligible"
  },
  {
    id: 12,
    name: "Riya Kapoor",
    enrollmentNo: "2023EC011",
    department: "Electronics",
    cgpa: 9.01,
    company: "Oracle",
    status: "Eligible"
  },
  {
    id: 13,
    name: "Mohit Jain",
    enrollmentNo: "2023ME012",
    department: "Mechanical",
    cgpa: 6.70,
    company: "L&T",
    status: "Eligible"
  },
  {
    id: 14,
    name: "Simran Kaur",
    enrollmentNo: "2023CS013",
    department: "Computer Science",
    cgpa: 8.54,
    company: "Amazon",
    status: "Eligible"
  },
  {
    id: 15,
    name: "Ayush Mishra",
    enrollmentNo: "2023IT014",
    department: "Information Technology",
    cgpa: 8.10,
    company: "Microsoft",
    status: "Eligible"
  },
  {
    id: 16,
    name: "Nisha Reddy",
    enrollmentNo: "2023EE015",
    department: "Electrical",
    cgpa: 7.82,
    company: "Tech Mahindra",
    status: "Eligible"
  },
  {
    id: 17,
    name: "Harsh Agarwal",
    enrollmentNo: "2023CS016",
    department: "Computer Science",
    cgpa: 9.45,
    company: "Google",
    status: "Eligible"
  },
  {
    id: 18,
    name: "Isha Singh",
    enrollmentNo: "2023EC017",
    department: "Electronics",
    cgpa: 8.02,
    company: "Intel",
    status: "Eligible"
  },
  {
    id: 19,
    name: "Deepak Sharma",
    enrollmentNo: "2023CE018",
    department: "Civil",
    cgpa: 6.90,
    company: "L&T",
    status: "Eligible"
  },
  {
    id: 20,
    name: "Kavya Nair",
    enrollmentNo: "2023CS019",
    department: "Computer Science",
    cgpa: 9.18,
    company: "Adobe",
    status: "Eligible"
  },
  {
    id: 21,
    name: "Sahil Arora",
    enrollmentNo: "2023IT020",
    department: "Information Technology",
    cgpa: 8.36,
    company: "IBM",
    status: "Eligible"
  },
  {
    id: 22,
    name: "Aarav Joshi",
    enrollmentNo: "2023CS021",
    department: "Computer Science",
    cgpa: 7.94,
    company: "Oracle",
    status: "Eligible"
  },
  {
    id: 23,
    name: "Tanvi Desai",
    enrollmentNo: "2023EC022",
    department: "Electronics",
    cgpa: 8.76,
    company: "Samsung",
    status: "Eligible"
  },
  {
    id: 24,
    name: "Yash Thakur",
    enrollmentNo: "2023ME023",
    department: "Mechanical",
    cgpa: 6.45,
    company: "Tata Motors",
    status: "Eligible"
  },
  {
    id: 25,
    name: "Meera Iyer",
    enrollmentNo: "2023CS024",
    department: "Computer Science",
    cgpa: 9.31,
    company: "Google",
    status: "Eligible"
  },
  {
    id: 26,
    name: "Aditya Roy",
    enrollmentNo: "2023IT025",
    department: "Information Technology",
    cgpa: 8.28,
    company: "Microsoft",
    status: "Eligible"
  },
  {
    id: 27,
    name: "Ritika Das",
    enrollmentNo: "2023EE026",
    department: "Electrical",
    cgpa: 7.64,
    company: "Siemens",
    status: "Eligible"
  },
  {
    id: 28,
    name: "Nitin Verma",
    enrollmentNo: "2023CS027",
    department: "Computer Science",
    cgpa: 8.91,
    company: "Amazon",
    status: "Eligible"
  },
  {
    id: 29,
    name: "Shreya Gupta",
    enrollmentNo: "2023IT028",
    department: "Information Technology",
    cgpa: 9.08,
    company: "Adobe",
    status: "Eligible"
  },
  {
    id: 30,
    name: "Manish Pandey",
    enrollmentNo: "2023CE029",
    department: "Civil",
    cgpa: 7.18,
    company: "Wipro",
    status: "Eligible"
  },
  {
    id: 31,
    name: "Aditi Sharma",
    enrollmentNo: "2023CS030",
    department: "Computer Science",
    cgpa: 8.59,
    company: "Google",
    status: "Eligible"
  },
  {
    id: 32,
    name: "Rohan Bansal",
    enrollmentNo: "2023IT031",
    department: "Information Technology",
    cgpa: 8.14,
    company: "Infosys",
    status: "Eligible"
  },
  {
    id: 33,
    name: "Sakshi Jain",
    enrollmentNo: "2023EC032",
    department: "Electronics",
    cgpa: 9.42,
    company: "Qualcomm",
    status: "Eligible"
  },
  {
    id: 34,
    name: "Abhishek Yadav",
    enrollmentNo: "2023CS033",
    department: "Computer Science",
    cgpa: 7.88,
    company: "Capgemini",
    status: "Eligible"
  },
  {
    id: 35,
    name: "Divya Menon",
    enrollmentNo: "2023IT034",
    department: "Information Technology",
    cgpa: 8.95,
    company: "Oracle",
    status: "Eligible"
  },
  {
    id: 36,
    name: "Akash Singh",
    enrollmentNo: "2023EE035",
    department: "Electrical",
    cgpa: 6.92,
    company: "ABB",
    status: "Eligible"
  },
  {
    id: 37,
    name: "Muskan Kapoor",
    enrollmentNo: "2023CS036",
    department: "Computer Science",
    cgpa: 9.12,
    company: "Google",
    status: "Eligible"
  },
  {
    id: 38,
    name: "Rahul Saini",
    enrollmentNo: "2023ME037",
    department: "Mechanical",
    cgpa: 7.50,
    company: "Bosch",
    status: "Eligible"
  },
  {
    id: 39,
    name: "Ishita Roy",
    enrollmentNo: "2023IT038",
    department: "Information Technology",
    cgpa: 8.72,
    company: "Amazon",
    status: "Eligible"
  },
  {
    id: 40,
    name: "Varun Khanna",
    enrollmentNo: "2023CS039",
    department: "Computer Science",
    cgpa: 8.44,
    company: "Microsoft",
    status: "Eligible"
  },
  {
    id: 41,
    name: "Payal Sharma",
    enrollmentNo: "2023EC040",
    department: "Electronics",
    cgpa: 7.81,
    company: "Intel",
    status: "Eligible"
  },
  {
    id: 42,
    name: "Kunal Mishra",
    enrollmentNo: "2023CS041",
    department: "Computer Science",
    cgpa: 9.28,
    company: "Google",
    status: "Eligible"
  },
  {
    id: 43,
    name: "Nidhi Gupta",
    enrollmentNo: "2023IT042",
    department: "Information Technology",
    cgpa: 8.37,
    company: "Adobe",
    status: "Eligible"
  },
  {
    id: 44,
    name: "Ashish Kumar",
    enrollmentNo: "2023EE043",
    department: "Electrical",
    cgpa: 6.68,
    company: "Siemens",
    status: "Eligible"
  },
  {
    id: 45,
    name: "Shruti Singh",
    enrollmentNo: "2023CS044",
    department: "Computer Science",
    cgpa: 8.86,
    company: "Oracle",
    status: "Eligible"
  },
  {
    id: 46,
    name: "Pranav Joshi",
    enrollmentNo: "2023IT045",
    department: "Information Technology",
    cgpa: 8.19,
    company: "IBM",
    status: "Eligible"
  },
  {
    id: 47,
    name: "Komal Verma",
    enrollmentNo: "2023EC046",
    department: "Electronics",
    cgpa: 9.05,
    company: "Samsung",
    status: "Eligible"
  },
  {
    id: 48,
    name: "Ritesh Patel",
    enrollmentNo: "2023CS047",
    department: "Computer Science",
    cgpa: 7.97,
    company: "Accenture",
    status: "Eligible"
  },
  {
    id: 49,
    name: "Pallavi Sharma",
    enrollmentNo: "2023IT048",
    department: "Information Technology",
    cgpa: 8.63,
    company: "Google",
    status: "Eligible"
  },
  {
    id: 50,
    name: "Nikhil Gupta",
    enrollmentNo: "2023CS049",
    department: "Computer Science",
    cgpa: 9.47,
    company: "Microsoft",
    status: "Eligible"
  },
];

export const nominatedStudents = [
  {
    id: 1,
    name: "Rahul Sharma",
    enrollmentNo: "CS21001",
    department: "Computer Science",
    cgpa: 9.32,
    company: "Google",
    role: "Software Engineer",
    package: "₹24 LPA",
    status: "Waiting",
    nominatedDate: "12 Jul 2026",
    email: "rahul.sharma@gmail.com",
    phone: "+91 9876543210",
    address: "Ranchi, Jharkhand",
    timeline: {
      nominated: "12 Jul 2026",
      waiting: "13 Jul 2026",
      Shortlisted: null,
      rejected: null,
    },
  },
  {
    id: 2,
    name: "Ayesha Khan",
    enrollmentNo: "CS21002",
    department: "Information Technology",
    cgpa: 8.91,
    company: "Microsoft",
    role: "Software Engineer",
    package: "₹22 LPA",
    status: "Shortlisted",
    nominatedDate: "10 Jul 2026",
    email: "ayesha.khan@gmail.com",
    phone: "+91 9876543211",
    address: "Jamshedpur, Jharkhand",
    timeline: {
      nominated: "10 Jul 2026",
      waiting: "12 Jul 2026",
      Shortlisted: "15 Jul 2026",
      rejected: null,
    },
  },
  {
    id: 3,
    name: "Aman Kumar",
    enrollmentNo: "CS21003",
    department: "Computer Science",
    cgpa: 8.75,
    company: "Amazon",
    role: "Data Analyst",
    package: "₹12 LPA",
    status: "Rejected",
    nominatedDate: "08 Jul 2026",
    email: "aman.kumar@gmail.com",
    phone: "+91 9876543212",
    address: "Patna, Bihar",
    timeline: {
      nominated: "08 Jul 2026",
      waiting: "11 Jul 2026",
      Shortlisted: null,
      rejected: "16 Jul 2026",
    },
  },
  {
    id: 4,
    name: "Priya Sharma",
    enrollmentNo: "CS21004",
    department: "Computer Science",
    cgpa: 9.41,
    company: "Google",
    role: "Software Engineer",
    package: "₹28 LPA",
    status: "Shortlisted",
    nominatedDate: "07 Jul 2026",
    email: "priya.sharma@gmail.com",
    phone: "+91 9876543213",
    address: "Delhi",
    timeline: {
      nominated: "07 Jul 2026",
      waiting: "10 Jul 2026",
      Shortlisted: "15 Jul 2026",
      rejected: null,
    },
  },
  {
    id: 5,
    name: "Rohit Verma",
    enrollmentNo: "CS21005",
    department: "Information Technology",
    cgpa: 8.83,
    company: "Adobe",
    role: "Frontend Developer",
    package: "₹18 LPA",
    status: "Waiting",
    nominatedDate: "09 Jul 2026",
    email: "rohit.verma@gmail.com",
    phone: "+91 9876543214",
    address: "Lucknow, UP",
    timeline: {
      nominated: "09 Jul 2026",
      waiting: "12 Jul 2026",
      Shortlisted: null,
      rejected: null,
    },
  },
  {
    id: 6,
    name: "Sneha Gupta",
    enrollmentNo: "CS21006",
    department: "Electronics",
    cgpa: 8.22,
    company: "TCS",
    role: "System Engineer",
    package: "₹7 LPA",
    status: "Shortlisted",
    nominatedDate: "06 Jul 2026",
    email: "sneha.gupta@gmail.com",
    phone: "+91 9876543215",
    address: "Kolkata, WB",
    timeline: {
      nominated: "06 Jul 2026",
      waiting: "09 Jul 2026",
      Shortlisted: "14 Jul 2026",
      rejected: null,
    },
  },
  {
    id: 7,
    name: "Karan Singh",
    enrollmentNo: "CS21007",
    department: "Mechanical",
    cgpa: 7.95,
    company: "Infosys",
    role: "Software Engineer",
    package: "₹8 LPA",
    status: "Rejected",
    nominatedDate: "07 Jul 2026",
    email: "karan.singh@gmail.com",
    phone: "+91 9876543216",
    address: "Jaipur, Rajasthan",
    timeline: {
      nominated: "07 Jul 2026",
      waiting: "11 Jul 2026",
      Shortlisted: null,
      rejected: "16 Jul 2026",
    },
  },
  {
    id: 8,
    name: "Neha Yadav",
    enrollmentNo: "CS21008",
    department: "Computer Science",
    cgpa: 9.18,
    company: "Flipkart",
    role: "Backend Developer",
    package: "₹20 LPA",
    status: "Shortlisted",
    nominatedDate: "08 Jul 2026",
    email: "neha.yadav@gmail.com",
    phone: "+91 9876543217",
    address: "Noida, UP",
    timeline: {
      nominated: "08 Jul 2026",
      waiting: "10 Jul 2026",
      Shortlisted: "15 Jul 2026",
      rejected: null,
    },
  },
  {
    id: 9,
    name: "Vikas Kumar",
    enrollmentNo: "CS21009",
    department: "Civil",
    cgpa: 7.88,
    company: "Capgemini",
    role: "Analyst",
    package: "₹6.5 LPA",
    status: "Waiting",
    nominatedDate: "10 Jul 2026",
    email: "vikas.kumar@gmail.com",
    phone: "+91 9876543218",
    address: "Bhopal, MP",
    timeline: {
      nominated: "10 Jul 2026",
      waiting: "13 Jul 2026",
      Shortlisted: null,
      rejected: null,
    },
  },
  {
    id: 10,
    name: "Ankit Mishra",
    enrollmentNo: "CS21010",
    department: "Computer Science",
    cgpa: 9.29,
    company: "Amazon",
    role: "SDE I",
    package: "₹24 LPA",
    status: "Shortlisted",
    nominatedDate: "05 Jul 2026",
    email: "ankit.mishra@gmail.com",
    phone: "+91 9876543219",
    address: "Varanasi, UP",
    timeline: {
      nominated: "05 Jul 2026",
      waiting: "08 Jul 2026",
      Shortlisted: "14 Jul 2026",
      rejected: null,
    },
  },
  {
    id: 11,
    name: "Pooja Singh",
    enrollmentNo: "CS21011",
    department: "Computer Science",
    cgpa: 8.92,
    company: "Oracle",
    role: "Software Engineer",
    package: "₹16 LPA",
    status: "Shortlisted",
    nominatedDate: "13 Jul 2026",
    email: "pooja.singh@gmail.com",
    phone: "+91 9876543220",
    address: "Ranchi, Jharkhand",
    timeline: {
      nominated: "13 Jul 2026",
      waiting: null,
      Shortlisted: "15 Jul 2026",
      Shortlisted: null,
      rejected: null,
    },
  },
  {
    id: 12,
    name: "Harsh Patel",
    enrollmentNo: "CS21012",
    department: "Information Technology",
    cgpa: 8.61,
    company: "IBM",
    role: "Associate Developer",
    package: "₹10 LPA",
    status: "Nominated",
    nominatedDate: "14 Jul 2026",
    email: "harsh.patel@gmail.com",
    phone: "+91 9876543221",
    address: "Ahmedabad, Gujarat",
    timeline: {
      nominated: "14 Jul 2026",
      waiting: null,
      Shortlisted: null,
      Shortlisted: null,
      rejected: null,
    },
  },
  {
    id: 13,
    name: "Nisha Roy",
    enrollmentNo: "CS21013",
    department: "Computer Science",
    cgpa: 9.15,
    company: "Adobe",
    role: "Frontend Developer",
    package: "₹18 LPA",
    status: "Shortlisted",
    nominatedDate: "12 Jul 2026",
    email: "nisha.roy@gmail.com",
    phone: "+91 9876543222",
    address: "Kolkata, West Bengal",
    timeline: {
      nominated: "12 Jul 2026",
      waiting: null,
      Shortlisted: "14 Jul 2026",
      Shortlisted: null,
      rejected: null,
    },
  },
  {
    id: 14,
    name: "Abhishek Kumar",
    enrollmentNo: "CS21014",
    department: "Electronics",
    cgpa: 8.44,
    company: "Wipro",
    role: "Project Engineer",
    package: "₹7.5 LPA",
    status: "Nominated",
    nominatedDate: "15 Jul 2026",
    email: "abhishek.kumar@gmail.com",
    phone: "+91 9876543223",
    address: "Patna, Bihar",
    timeline: {
      nominated: "15 Jul 2026",
      waiting: null,
      Shortlisted: null,
      Shortlisted: null,
      rejected: null,
    },
  },
  {
    id: 15,
    name: "Meera Joshi",
    enrollmentNo: "CS21015",
    department: "Computer Science",
    cgpa: 9.05,
    company: "Cisco",
    role: "Network Engineer",
    package: "₹15 LPA",
    status: "Shortlisted",
    nominatedDate: "11 Jul 2026",
    email: "meera.joshi@gmail.com",
    phone: "+91 9876543224",
    address: "Pune, Maharashtra",
    timeline: {
      nominated: "11 Jul 2026",
      waiting: null,
      Shortlisted: "13 Jul 2026",
      Shortlisted: null,
      rejected: null,
    },
  },
  {
    id: 16,
    name: "Yash Agarwal",
    enrollmentNo: "CS21016",
    department: "Information Technology",
    cgpa: 8.76,
    company: "Paytm",
    role: "Software Engineer",
    package: "₹14 LPA",
    status: "Nominated",
    nominatedDate: "16 Jul 2026",
    email: "yash.agarwal@gmail.com",
    phone: "+91 9876543225",
    address: "Indore, MP",
    timeline: {
      nominated: "16 Jul 2026",
      waiting: null,
      Shortlisted: null,
      Shortlisted: null,
      rejected: null,
    },
  },
  {
    id: 17,
    name: "Kavya Sharma",
    enrollmentNo: "CS21017",
    department: "Computer Science",
    cgpa: 9.27,
    company: "Samsung",
    role: "Software Engineer",
    package: "₹17 LPA",
    status: "Shortlisted",
    nominatedDate: "13 Jul 2026",
    email: "kavya.sharma@gmail.com",
    phone: "+91 9876543226",
    address: "Delhi",
    timeline: {
      nominated: "13 Jul 2026",
      waiting: null,
      Shortlisted: "16 Jul 2026",
      Shortlisted: null,
      rejected: null,
    },
  },
  {
    id: 18,
    name: "Rajat Sinha",
    enrollmentNo: "CS21018",
    department: "Mechanical",
    cgpa: 8.03,
    company: "L&T",
    role: "Graduate Engineer",
    package: "₹8 LPA",
    status: "Nominated",
    nominatedDate: "15 Jul 2026",
    email: "rajat.sinha@gmail.com",
    phone: "+91 9876543227",
    address: "Dhanbad, Jharkhand",
    timeline: {
      nominated: "15 Jul 2026",
      waiting: null,
      Shortlisted: null,
      Shortlisted: null,
      rejected: null,
    },
  },
  {
    id: 19,
    name: "Tanvi Rao",
    enrollmentNo: "CS21019",
    department: "Computer Science",
    cgpa: 9.38,
    company: "Goldman Sachs",
    role: "Analyst",
    package: "₹28 LPA",
    status: "Shortlisted",
    nominatedDate: "12 Jul 2026",
    email: "tanvi.rao@gmail.com",
    phone: "+91 9876543228",
    address: "Hyderabad, Telangana",
    timeline: {
      nominated: "12 Jul 2026",
      waiting: null,
      Shortlisted: "15 Jul 2026",
      Shortlisted: null,
      rejected: null,
    },
  },
  {
    id: 20,
    name: "Sahil Khan",
    enrollmentNo: "CS21020",
    department: "Information Technology",
    cgpa: 8.57,
    company: "Deloitte",
    role: "Business Analyst",
    package: "₹11 LPA",
    status: "Nominated",
    nominatedDate: "16 Jul 2026",
    email: "sahil.khan@gmail.com",
    phone: "+91 9876543229",
    address: "Jamshedpur, Jharkhand",
    timeline: {
      nominated: "16 Jul 2026",
      waiting: null,
      Shortlisted: null,
      Shortlisted: null,
      rejected: null,
    },
  }
]

export const shortlistedStudents = [
  {
    id: 1,
    student: "Rahul Sharma",
    company: "Google",
    role: "Software Engineer",
    package: "₹32 LPA",
    shortlistedDate: "12 Jul 2026",
    status: "Shortlisted",
    selected: true,
  },
  {
    id: 2,
    student: "Sneha Patel",
    company: "Microsoft",
    role: "Cloud Engineer",
    package: "₹28 LPA",
    shortlistedDate: "13 Jul 2026",
    status: "Shortlisted",
    selected: true,
  },
  {
    id: 3,
    student: "Amit Kumar",
    company: "Amazon",
    role: "SDE I",
    package: "₹30 LPA",
    shortlistedDate: "13 Jul 2026",
    status: "Shortlisted",
    selected: true,
  },
  {
    id: 4,
    student: "Priya Verma",
    company: "Deloitte",
    role: "Business Analyst",
    package: "₹9 LPA",
    shortlistedDate: "14 Jul 2026",
    status: "Shortlisted",
    selected: true,
  },
  {
    id: 5,
    student: "Rohan Gupta",
    company: "Infosys",
    role: "Systems Engineer",
    package: "₹7.2 LPA",
    shortlistedDate: "14 Jul 2026",
    status: "Shortlisted",
    selected: true,
  },
  {
    id: 6,
    student: "Neha Sharma",
    company: "Google",
    role: "UI Developer",
    package: "₹24 LPA",
    shortlistedDate: "15 Jul 2026",
    status: "Shortlisted",
    selected: true,
  },
  {
    id: 7,
    student: "Vikram Singh",
    company: "Amazon",
    role: "Data Engineer",
    package: "₹26 LPA",
    shortlistedDate: "15 Jul 2026",
    status: "Shortlisted",
    selected: true,
  },
  {
    id: 8,
    student: "Ananya Das",
    company: "Microsoft",
    role: "Software Engineer",
    package: "₹27 LPA",
    shortlistedDate: "16 Jul 2026",
    status: "Shortlisted",
    selected: true,
  },
  {
    id: 9,
    student: "Aditya Mishra",
    company: "Deloitte",
    role: "Consultant",
    package: "₹10 LPA",
    shortlistedDate: "16 Jul 2026",
    status: "Shortlisted",
    selected: true,
  },
  {
    id: 10,
    student: "Pooja Yadav",
    company: "Google",
    role: "Backend Developer",
    package: "₹29 LPA",
    shortlistedDate: "17 Jul 2026",
    status: "Shortlisted",
    selected: true,
  },
  {
    id: 11,
    student: "Karan Mehta",
    company: "Infosys",
    role: "Full Stack Developer",
    package: "₹8.5 LPA",
    shortlistedDate: "17 Jul 2026",
    status: "Shortlisted",
    selected: true,
  },
  {
    id: 12,
    student: "Shreya Roy",
    company: "TCS",
    role: "Software Engineer",
    package: "₹7.8 LPA",
    shortlistedDate: "18 Jul 2026",
    status: "Shortlisted",
    selected: false,
  },
  {
    id: 13,
    student: "Arjun Nair",
    company: "Amazon",
    role: "DevOps Engineer",
    package: "₹25 LPA",
    shortlistedDate: "18 Jul 2026",
    status: "Shortlisted",
    selected: false,
  },
  {
    id: 14,
    student: "Ishita Jain",
    company: "Microsoft",
    role: "AI Engineer",
    package: "₹31 LPA",
    shortlistedDate: "19 Jul 2026",
    status: "Shortlisted",
    selected: false,
  },
  {
    id: 15,
    student: "Saurabh Verma",
    company: "TCS",
    role: "Java Developer",
    package: "₹8.2 LPA",
    shortlistedDate: "19 Jul 2026",
    status: "Shortlisted",
    selected: false,
  },
  {
    id: 16,
    student: "Ayush Raj",
    company: "Amazon",
    role: "Frontend Developer",
    package: "₹22 LPA",
    shortlistedDate: "20 Jul 2026",
    status: "Shortlisted",
    selected: false,
  },
  {
    id: 17,
    student: "Nikhil Sharma",
    company: "Amazon",
    role: "Backend Developer",
    package: "₹24 LPA",
    shortlistedDate: "20 Jul 2026",
    status: "Shortlisted",
    selected: false,
  },
  {
    id: 18,
    student: "Ritika Singh",
    company: "Amazon",
    role: "Software Development Engineer",
    package: "₹30 LPA",
    shortlistedDate: "21 Jul 2026",
    status: "Shortlisted",
    selected: false,
  },
  {
    id: 19,
    student: "Harsh Verma",
    company: "Amazon",
    role: "Data Engineer",
    package: "₹26 LPA",
    shortlistedDate: "21 Jul 2026",
    status: "Shortlisted",
    selected: false,
  },
  {
    id: 20,
    student: "Ankit Kumar",
    company: "Amazon",
    role: "Cloud Support Engineer",
    package: "₹18 LPA",
    shortlistedDate: "22 Jul 2026",
    status: "Shortlisted",
    selected: false,
  },
  {
    id: 21,
    student: "Sakshi Gupta",
    company: "Amazon",
    role: "Quality Assurance Engineer",
    package: "₹17 LPA",
    shortlistedDate: "22 Jul 2026",
    status: "Shortlisted",
    selected: false,
  },
  {
    id: 22,
    student: "Yash Agarwal",
    company: "Amazon",
    role: "DevOps Engineer",
    package: "₹27 LPA",
    shortlistedDate: "23 Jul 2026",
    status: "Shortlisted",
    selected: false,
    
  },
  {
    id: 23,
    student: "Mehak Arora",
    company: "Amazon",
    role: "Machine Learning Engineer",
    package: "₹33 LPA",
    shortlistedDate: "23 Jul 2026",
    status: "Shortlisted",
    selected: true,
  },
  {
    id: 24,
    student: "Aditya Sinha",
    company: "Amazon",
    role: "Site Reliability Engineer",
    package: "₹29 LPA",
    shortlistedDate: "24 Jul 2026",
    status: "Shortlisted",
    selected: false,
  },
  {
    id: 25,
    student: "Priyanshu Mishra",
    company: "Amazon",
    role: "Full Stack Developer",
    package: "₹25 LPA",
    shortlistedDate: "24 Jul 2026",
    status: "Shortlisted",
    selected: true,
  },
];

export const nominationApiResponse = {
  success: true,
  data: {
    eligibleStudents,
    shortlistedStudents
  }
};