/**
 * Formats a ISO date string to a human-readable format.
 */
export const formatDate = (dateString) => {
  if (!dateString) return "";
  const options = { year: 'numeric', month: 'short', day: 'numeric' };
  return new Date(dateString).toLocaleDateString('en-US', options);
};

/**
 * Utility to download a file blob in the browser.
 */
export const downloadBlob = (content, filename, contentType) => {
  const blob = new Blob([content], { type: contentType });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
};

/**
 * Converts report array data to CSV string.
 */
export const generateCSVContent = (reports) => {
  const headers = ["ID", "Report Name", "Type", "Generated On", "Status", "Department", "Company", "Batch", "Size", "Generated By"];
  const rows = reports.map(r => [
    r.id,
    `"${r.reportName.replace(/"/g, '""')}"`,
    r.type,
    r.generatedOn,
    r.status,
    r.department || "N/A",
    r.company || "N/A",
    r.batch || "N/A",
    r.size || "0 KB",
    r.generatedBy || "System"
  ]);
  
  return [headers.join(","), ...rows.map(row => row.join(","))].join("\n");
};

/**
 * Generates an Excel-compatible XML spreadsheet content.
 */
export const generateExcelXMLContent = (reports) => {
  let xml = `<?xml version="1.0"?>\n<Workbook xmlns="urn:schemas-microsoft-com:office:spreadsheet"\n`;
  xml += ` xmlns:o="urn:schemas-microsoft-com:office:office"\n`;
  xml += ` xmlns:x="urn:schemas-microsoft-com:office:excel"\n`;
  xml += ` xmlns:ss="urn:schemas-microsoft-com:office:spreadsheet"\n`;
  xml += ` xmlns:html="http://www.w3.org/TR/REC-html40">\n`;
  xml += ` <Worksheet ss:Name="Reports List">\n  <Table>\n`;
  
  // Headers
  xml += `   <Row>\n`;
  const headers = ["ID", "Report Name", "Type", "Generated On", "Status", "Department", "Company", "Batch", "Size", "Generated By"];
  headers.forEach(header => {
    xml += `    <Cell><Data ss:Type="String">${header}</Data></Cell>\n`;
  });
  xml += `   </Row>\n`;
  
  // Data
  reports.forEach(r => {
    xml += `   <Row>\n`;
    xml += `    <Cell><Data ss:Type="Number">${r.id}</Data></Cell>\n`;
    xml += `    <Cell><Data ss:Type="String">${r.reportName}</Data></Cell>\n`;
    xml += `    <Cell><Data ss:Type="String">${r.type}</Data></Cell>\n`;
    xml += `    <Cell><Data ss:Type="String">${r.generatedOn}</Data></Cell>\n`;
    xml += `    <Cell><Data ss:Type="String">${r.status}</Data></Cell>\n`;
    xml += `    <Cell><Data ss:Type="String">${r.department || "N/A"}</Data></Cell>\n`;
    xml += `    <Cell><Data ss:Type="String">${r.company || "N/A"}</Data></Cell>\n`;
    xml += `    <Cell><Data ss:Type="String">${r.batch || "N/A"}</Data></Cell>\n`;
    xml += `    <Cell><Data ss:Type="String">${r.size || "0 KB"}</Data></Cell>\n`;
    xml += `    <Cell><Data ss:Type="String">${r.generatedBy || "System"}</Data></Cell>\n`;
    xml += `   </Row>\n`;
  });
  
  xml += `  </Table>\n </Worksheet>\n</Workbook>`;
  return xml;
};

/**
 * Returns mock tabular and chart data for previewing different types of reports.
 */
export const getReportMockDetails = (report) => {
  if (!report) return null;
  
  const baseData = {
    id: report.id,
    title: report.reportName,
    type: report.type,
    generatedOn: report.generatedOn,
    generatedBy: report.generatedBy,
    status: report.status,
    filtersApplied: {
      department: report.department || "All",
      company: report.company || "All",
      batch: report.batch || "All"
    }
  };

  switch (report.type) {
    case "PLACEMENTS":
      return {
        ...baseData,
        summary: {
          totalRegistered: 340,
          totalPlaced: 289,
          placementRate: "85%",
          highestPackage: "44 LPA",
          averagePackage: "7.8 LPA",
          medianPackage: "6.5 LPA"
        },
        records: [
          { sNo: 1, rollNo: "CSE2601", studentName: "Aarav Sharma", department: "CSE", company: "Google", package: "44 LPA", status: "Selected" },
          { sNo: 2, rollNo: "CSE2642", studentName: "Isha Patel", department: "CSE", company: "Microsoft", package: "28 LPA", status: "Selected" },
          { sNo: 3, rollNo: "ECE2608", studentName: "Kabir Singh", department: "ECE", company: "TCS", package: "7 LPA", status: "Selected" },
          { sNo: 4, rollNo: "ME2614", studentName: "Rohan Verma", department: "ME", company: "Tata Motors", package: "9 LPA", status: "Selected" },
          { sNo: 5, rollNo: "CSE2611", studentName: "Neha Gupta", department: "CSE", company: "Amazon", package: "32 LPA", status: "Selected" }
        ],
        chartData: [
          { label: "CSE", rate: 94 },
          { label: "ECE", rate: 82 },
          { label: "ME", rate: 70 },
          { label: "CE", rate: 65 },
          { label: "MBA", rate: 88 }
        ]
      };
      
    case "STUDENTS":
      return {
        ...baseData,
        summary: {
          totalStudents: 1200,
          activeJobSeekers: 850,
          completedTraining: 980,
          certifiedInSkills: 670
        },
        records: [
          { sNo: 1, rollNo: "CSE2601", studentName: "Aarav Sharma", CGPA: "9.2", skills: "React, Node, Python", mockTestScore: "85%", attendance: "94%" },
          { sNo: 2, rollNo: "CSE2642", studentName: "Isha Patel", CGPA: "8.9", skills: "Java, Spring Boot", mockTestScore: "78%", attendance: "91%" },
          { sNo: 3, rollNo: "ECE2608", studentName: "Kabir Singh", CGPA: "7.8", skills: "C++, Embedded C", mockTestScore: "72%", attendance: "88%" },
          { sNo: 4, rollNo: "ME2614", studentName: "Rohan Verma", CGPA: "8.1", skills: "AutoCAD, SolidWorks", mockTestScore: "68%", attendance: "85%" },
          { sNo: 5, rollNo: "CSE2611", studentName: "Neha Gupta", CGPA: "9.5", skills: "React, AWS, Docker", mockTestScore: "92%", attendance: "98%" }
        ],
        chartData: [
          { label: "Above 9.0 CGPA", count: 120 },
          { label: "8.0 - 9.0 CGPA", count: 430 },
          { label: "7.0 - 8.0 CGPA", count: 380 },
          { label: "Below 7.0 CGPA", count: 270 }
        ]
      };

    case "COMPANIES":
      return {
        ...baseData,
        summary: {
          totalVisiting: 48,
          activeDrives: 12,
          totalOffersMade: 180,
          highestOffer: "44 LPA"
        },
        records: [
          { sNo: 1, companyName: "Google", jobRole: "Software Engineer", vacancy: 10, applications: 150, offersReleased: 4, package: "44 LPA" },
          { sNo: 2, companyName: "Microsoft", jobRole: "SWE Associate", vacancy: 8, applications: 120, offersReleased: 3, package: "28 LPA" },
          { sNo: 3, companyName: "Amazon", jobRole: "Cloud Support", vacancy: 15, applications: 200, offersReleased: 6, package: "32 LPA" },
          { sNo: 4, companyName: "TCS", jobRole: "Ninja / Digital", vacancy: 120, applications: 600, offersReleased: 78, package: "3.6 - 7.0 LPA" },
          { sNo: 5, companyName: "Tata Motors", jobRole: "Graduate Engineer Trainee", vacancy: 5, applications: 80, offersReleased: 3, package: "9 LPA" }
        ],
        chartData: [
          { label: "TCS", offers: 78 },
          { label: "Infosys", offers: 45 },
          { label: "Cognizant", offers: 32 },
          { label: "Amazon", offers: 6 },
          { label: "Google", offers: 4 }
        ]
      };

    case "DEPARTMENTS":
      return {
        ...baseData,
        summary: {
          totalDepts: 5,
          topPerformingDept: "CSE (94% Placed)",
          avgDeptSalary: "7.2 LPA",
          totalOffers: 289
        },
        records: [
          { sNo: 1, deptName: "Computer Science (CSE)", totalStudents: 150, registered: 140, placed: 132, percentage: "94.3%", avgSalary: "9.2 LPA" },
          { sNo: 2, deptName: "Electronics & Comm (ECE)", totalStudents: 120, registered: 100, placed: 82, percentage: "82.0%", avgSalary: "6.5 LPA" },
          { sNo: 3, deptName: "Mechanical Eng (ME)", totalStudents: 90, registered: 60, placed: 42, percentage: "70.0%", avgSalary: "5.4 LPA" },
          { sNo: 4, deptName: "Civil Eng (CE)", totalStudents: 60, registered: 30, placed: 19, percentage: "63.3%", avgSalary: "4.8 LPA" },
          { sNo: 5, deptName: "Management (MBA)", totalStudents: 60, registered: 50, placed: 44, percentage: "88.0%", avgSalary: "8.1 LPA" }
        ],
        chartData: [
          { label: "CSE", avg: 9.2 },
          { label: "ECE", avg: 6.5 },
          { label: "ME", avg: 5.4 },
          { label: "CE", avg: 4.8 },
          { label: "MBA", avg: 8.1 }
        ]
      };

    case "DASHBOARD":
      return {
        ...baseData,
        summary: {
          totalApplications: 1240,
          overallSelectRatio: "23%",
          monthlyGrowthRate: "+14%",
          trainingEfficiency: "89%"
        },
        records: [
          { sNo: 1, month: "July", drivesHeld: 4, applications: 180, shortlists: 45, finalSelections: 18, selectRatio: "10%" },
          { sNo: 2, month: "August", drivesHeld: 8, applications: 320, shortlists: 92, finalSelections: 42, selectRatio: "13%" },
          { sNo: 3, month: "September", drivesHeld: 12, applications: 410, shortlists: 124, finalSelections: 68, selectRatio: "16.5%" },
          { sNo: 4, month: "October", drivesHeld: 15, applications: 330, shortlists: 180, finalSelections: 161, selectRatio: "48.7%" }
        ],
        chartData: [
          { label: "July", selections: 18 },
          { label: "August", selections: 42 },
          { label: "September", selections: 68 },
          { label: "October", selections: 161 }
        ]
      };

    case "DRIVES":
      return {
        ...baseData,
        summary: {
          driveName: report.reportName,
          status: "Completed",
          eligibleCandidates: 140,
          appeared: 128,
          writtenTestPassed: 42,
          interviewSelected: 8
        },
        records: [
          { sNo: 1, stage: "1. Eligibility Filter", count: 140, percentage: "100%" },
          { sNo: 2, stage: "2. Online Coding Test", count: 128, percentage: "91.4%" },
          { sNo: 3, stage: "3. Technical Interview", count: 42, percentage: "30.0%" },
          { sNo: 4, stage: "4. HR & Final Round", count: 12, percentage: "8.5%" },
          { sNo: 5, stage: "5. Selected Offers", count: 8, percentage: "5.7%" }
        ],
        chartData: [
          { label: "Appeared", count: 128 },
          { label: "Test Passed", count: 42 },
          { label: "Interviews", count: 12 },
          { label: "Selected", count: 8 }
        ]
      };

    default:
      return baseData;
  }
};
