/**
 * Formats a ISO date string to a human-readable format.
 */
export const formatDate = (dateString) => {
  if (!dateString) return "";
  const options = { year: 'numeric', month: 'short', day: 'numeric' };
  return new Date(dateString).toLocaleDateString('en-US', options);
};

/**
 * Utility to download a file blob in the browser.
 */
export const downloadBlob = (content, filename, contentType) => {
  const blob = new Blob([content], { type: contentType });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
};

/**
 * Converts report array data to CSV string.
 */
export const generateCSVContent = (reports) => {
  const headers = ["ID", "Report Name", "Type", "Generated On", "Status", "Department", "Company", "Batch", "Size", "Generated By"];
  const rows = reports.map(r => [
    r.id,
    `"${r.reportName.replace(/"/g, '""')}"`,
    r.type,
    r.generatedOn,
    r.status,
    r.department || "N/A",
    r.company || "N/A",
    r.batch || "N/A",
    r.size || "0 KB",
    r.generatedBy || "System"
  ]);
  
  return [headers.join(","), ...rows.map(row => row.join(","))].join("\n");
};

/**
 * Generates an Excel-compatible XML spreadsheet content.
 */
export const generateExcelXMLContent = (reports) => {
  let xml = `<?xml version="1.0"?>\n<Workbook xmlns="urn:schemas-microsoft-com:office:spreadsheet"\n`;
  xml += ` xmlns:o="urn:schemas-microsoft-com:office:office"\n`;
  xml += ` xmlns:x="urn:schemas-microsoft-com:office:excel"\n`;
  xml += ` xmlns:ss="urn:schemas-microsoft-com:office:spreadsheet"\n`;
  xml += ` xmlns:html="http://www.w3.org/TR/REC-html40">\n`;
  xml += ` <Worksheet ss:Name="Reports List">\n  <Table>\n`;
  
  // Headers
  xml += `   <Row>\n`;
  const headers = ["ID", "Report Name", "Type", "Generated On", "Status", "Department", "Company", "Batch", "Size", "Generated By"];
  headers.forEach(header => {
    xml += `    <Cell><Data ss:Type="String">${header}</Data></Cell>\n`;
  });
  xml += `   </Row>\n`;
  
  // Data
  reports.forEach(r => {
    xml += `   <Row>\n`;
    xml += `    <Cell><Data ss:Type="Number">${r.id}</Data></Cell>\n`;
    xml += `    <Cell><Data ss:Type="String">${r.reportName}</Data></Cell>\n`;
    xml += `    <Cell><Data ss:Type="String">${r.type}</Data></Cell>\n`;
    xml += `    <Cell><Data ss:Type="String">${r.generatedOn}</Data></Cell>\n`;
    xml += `    <Cell><Data ss:Type="String">${r.status}</Data></Cell>\n`;
    xml += `    <Cell><Data ss:Type="String">${r.department || "N/A"}</Data></Cell>\n`;
    xml += `    <Cell><Data ss:Type="String">${r.company || "N/A"}</Data></Cell>\n`;
    xml += `    <Cell><Data ss:Type="String">${r.batch || "N/A"}</Data></Cell>\n`;
    xml += `    <Cell><Data ss:Type="String">${r.size || "0 KB"}</Data></Cell>\n`;
    xml += `    <Cell><Data ss:Type="String">${r.generatedBy || "System"}</Data></Cell>\n`;
    xml += `   </Row>\n`;
  });
  
  xml += `  </Table>\n </Worksheet>\n</Workbook>`;
  return xml;
};
